# Generated by Django 4.2.5 on 2023-09-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_recipient_alter_book_owner'),
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(
                blank=True, related_name='wishlists', to='books.book'),
        ),
    ]
