# Generated by Django 4.2.5 on 2023-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_owner_book_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
