# Generated by Django 4.2.5 on 2023-09-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_condition_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
